class _PCAssemblyError(Exception): ...


class IncompatibleComponentError(_PCAssemblyError): ...


class SlotNotAvailableError(_PCAssemblyError): ...


class ComponentAlreadyInstalledError(_PCAssemblyError): ...


class ComponentNotFoundError(_PCAssemblyError): ...


class InsufficientPowerError(_PCAssemblyError): ...


class EmptyBuildError(_PCAssemblyError): ...
