[pytest]
minversion = 6.0
addopts = -v -s -ra -q
testpaths = 
  tests
  integration
markers = 
  critical: Mark most critical tests for business
  slow: Mark slowest tests in this suite
  unittest: Mark the unit tests of the suite
  integration: Mark the integration tests of the suite
  validations: Mark the validations tests of the suite
  raise_exception: Mark the unit tests that should raise an exception
  discounts: Mark the unit tests that is a discount